// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twqncrzkbbvokxbfqtwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3cW5jcnprYmJ2b2t4YmZxdHd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNTU1NDEsImV4cCI6MjA3MjYzMTU0MX0.9t2xvpng3NxwuvtkXbzFdRmwS4QV4e8Y-JjeAb0MqDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});